#' Read meth, UNmeth, and meth_level data, the corresponding column name is \\.name$
#'
#' @param file_tmp DNA methylation or chromatin accessibility matrix
#' @param string_data sample type information, such as meth, UNmeth, methlevel
#'
#' @return sample data after selecting columns
#' @export
#'
#' @examples
Read_file_colname <- function(file_tmp,string_data){
  file_data <- file_tmp
  string_tmp <- string_data
  string_col <- paste0("\\.",string_tmp)
  string_col2 <- paste0(string_col,"$")

  column_indices <- grep(string_col2, names(file_data), value = TRUE)
  file_data_meth <- file_data[,column_indices]
  # file_data_meth <- cbind(rownames(file_data),file_data_meth)
  rownames(file_data_meth) <- rownames(file_tmp)
  return(file_data_meth)
}


#' Coverage files to text files
#'
#' @param cov_file site file name
#' @param cov_file_data site data
#' @param region_data chromosome data
#' @param chr_data chromosomal physical fragment
#' @param suffixname_data file extension
#' @param method_type select the Site or Level method
#'
#' @return DNA methylation or chromatin accessibility matrix
#' @export
#'
#' @examples
Coverage_to_data <- function(cov_file, cov_file_data, region_data, chr_data, suffixname_data=".cov.gz", method_type) {
  # 1. Data Preprocessing
  # Add unique IDs to region_data to facilitate restoring order or establishing associations after aggregation.
  region_target <- region_data %>%
    filter(chr %in% chr_data) %>%
    mutate(region_uid = paste(chr, start, end, sep = ":")) # Create a Unique Identifier

  cov_data <- cov_file_data
  colnames(cov_data) <- c("chr", "start", "end", "methlevel", "meth", "UNmeth")

  # Pre-filter the required chromosomes to reduce subsequent data volume.
  cov_data_filtered <- cov_data %>%
    filter(chr %in% chr_data)

  suffixname <- paste0("\\", suffixname_data)

  # 2. Generate column names
  cov_file_name <- basename(cov_file)
  split_result <- strsplit(cov_file_name, suffixname)[[1]][1]

  if (method_type == "Site") {
    col_names <- paste0(split_result, c(".site", ".nonsite"))
  } else if (method_type == "Level") {
    col_names <- paste0(split_result, c(".sites", ".level"))
  } else {
    stop("Unknown method_type")
  }

  # Initialize the results list
  result_list <- list()

  # 3. Process by chromosome cycle (to avoid memory overflow while leveraging dplyr's join for acceleration)
  for (k in chr_data) {

    # Retrieve region and locus data for the current chromosome
    r_chr <- region_target %>% filter(chr == k)
    c_chr <- cov_data_filtered %>% filter(chr == k)

    if (nrow(r_chr) == 0) next

    # Core Optimization: Replace loops with range joins
    # Logic: Region.start <= Site.start AND Region.end >= Site.start
    # Note: The site position in cov_data is determined by the ‘start’ column

    # Left join: Retain all Regions, even if no matching Site is found.
    # require dplyr >= 1.1.0
    merged_data <- left_join(
      r_chr,
      c_chr,
      by = join_by(chr == chr, start <= start, end >= start)
    )

    # 4. Perform aggregation calculations based on method_type
    if (method_type == "Site") {
      summary_df <- merged_data %>%
        group_by(region_uid) %>%
        summarise(
          val1 = sum(meth, na.rm = TRUE),
          val2 = sum(UNmeth, na.rm = TRUE),
          .groups = "drop"
        )
    } else if (method_type == "Level") {
      summary_df <- merged_data %>%
        group_by(region_uid) %>%
        summarise(
          val1 = sum(!is.na(methlevel)),
          # If no site is present, `mean` returns `NaN`. Here, it is treated as `NA` to maintain consistency with the original code logic.
          val2 = ifelse(val1 > 0, mean(methlevel, na.rm = TRUE), NA),
          .groups = "drop"
        )
    }

    # Store the calculation results in a list
    result_list[[k]] <- summary_df
  }

  # 5. Merge results and format
  final_df <- bind_rows(result_list)

  # Ensure the result order matches the input region_target
  # Left join back to region_target to restore the original order and unmatched rows (though already handled above, this serves as a double safeguard)
  final_output <- region_target %>%
    select(region_uid) %>%
    left_join(final_df, by = "region_uid")

  # Set Row Names
  # The rownames generated by the source code follow the format chr:start-end.
  rownames(final_output) <- final_output$region_uid

  # Set column names and remove auxiliary columns
  final_output <- final_output %>% select(val1, val2)
  colnames(final_output) <- col_names
  return(final_output)
}

#' Methlevel quality control
#'
#' @param file_data Data requiring column quality control
#' @param sample_cutoff Percentage of NA Values
#'
#' @returns Data after quality control
#' @export
#'
#' @examples
QC_data <- function(file_data,sample_cutoff=0.8){
  samples_keep <- colMeans(is.na(file_data)) < sample_cutoff
  CpG_data_clean <- file_data[, samples_keep]

  cat("After filtering the samples, the matrix dimensions:", dim(CpG_data_clean), "\n")
  cat("Number of excluded samples:", ncol(file_data) - ncol(CpG_data_clean), "\n")
  return(CpG_data_clean)
}


#' Difference level chart
#'
#' @param CpG_DEG_file_data Methylation differences information
#' @param GpC_DEG_file_data Chromitan difference information
#'
#' @return CpG and GpC differences data
#' @export
#'
#' @examples
DEG_diff_process <- function(CpG_DEG_file_data,GpC_DEG_file_data){
  # CpG_DEG_file_data <- read.csv(CpG_DEG_files)
  # GpC_DEG_file_data <- read.csv(GpC_DEG_files)

  CpG_GpC_chrdata <- intersect(CpG_DEG_file_data$chrdata,GpC_DEG_file_data$chrdata)

  CpG_DEG_data_choose_union <- CpG_DEG_file_data %>%
    filter(chrdata %in% CpG_GpC_chrdata)

  GpC_DEG_data_choose_union <- GpC_DEG_file_data %>%
    filter(chrdata %in% CpG_GpC_chrdata)

  colnames(CpG_DEG_data_choose_union) <- paste0("CpG.", colnames(CpG_DEG_data_choose_union))
  colnames(GpC_DEG_data_choose_union) <- paste0("GpC.", colnames(GpC_DEG_data_choose_union))

  DEG_data_union <- cbind(CpG_DEG_data_choose_union,GpC_DEG_data_choose_union)
  return(DEG_data_union)
}

#' Calculate the silhouette coefficient
#'
#' @param file_data Dimensionality reduction data
#' @param file_type Dimensionality-Reduced data types
#'
#' @returns Mean Silhouette coefficient value
#' @export
#'
#' @examples
SC_process <- function(file_data,file_type="UMAP"){
  if (file_type=="UMAP") {
    umap_coords <- file_data[,c(1,2)]
    umap_groups <- file_data$Stage
    umap_dist <- dist(umap_coords)
    sil_umap <- silhouette(as.numeric(factor(umap_groups)), umap_dist)
    mean_sil_umap <- mean(sil_umap[, 3])
    cat("UMAP Mean Silhouette Coefficient Value:", round(mean_sil_umap, 3), "\n")
    return(mean_sil_umap)
  }else if(file_type=="PCA"){
    pca_coords <- file_data[,c(1,2)]
    pca_groups <- file_data$Stage
    pca_dist <- dist(pca_coords)
    sil_pca <- silhouette(as.numeric(factor(pca_groups)), pca_dist)
    mean_sil_pca <- mean(sil_pca[, 3])
    cat("PCA Mean Silhouette Coefficient Value:", round(mean_sil_pca, 3), "\n")
    return(mean_sil_pca)
  }else if(file_type=="MDS"){
    mds_coords <- file_data[,c(1,2)]
    mds_groups <- file_data$Stage
    mds_dist <- dist(mds_coords)
    sil_mds <- silhouette(as.numeric(factor(mds_groups)), mds_dist)
    mean_sil_mds <- mean(sil_mds[, 3])
    cat("MDS Mean Silhouette Coefficient Value:", round(mean_sil_mds, 3), "\n")
    return(mean_sil_mds)
  }
}
